(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},h;if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var k;a:{var l={w:!0},m={};try{m.__proto__=l;k=m.w;break a}catch(a){}k=!1}h=k?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var n=h,p=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},q=p(this);var r=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},t=function(a){if(r(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&r(a))return a;return null},u=function(a,b){return b!=a.getAttribute("source")?(a.setAttribute("source",b),!0):!1};var v=function(a,b){var c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d)},w=function(a,b,c){var d=function(f){a.removeEventListener(b,d);c(f)};a.addEventListener(b,d)};var x=function(a){return/^[\s\xa0]*$/.test(a)};var y=function(){this.v=""};y.prototype.toString=function(){return"SafeStyle{"+this.v+"}"};y.prototype.l=function(a){this.v=a};(new y).l("");var z=function(){this.u=""};z.prototype.toString=function(){return"SafeStyleSheet{"+this.u+"}"};z.prototype.l=function(a){this.u=a};(new z).l("");var A={D:"alignment",F:"bgcolor",G:"disabled",H:"down-image",I:"over-image",J:"scaling",K:"up-image"},B=[],C=0,D;for(D in A)B[C++]=A[D];var E=function(){var a=HTMLElement.call(this)||this;a.c="gwd_imagebutton_"+(2147483648*Math.random()|0);a.a=null;a.i=null;a.b=!1;a.s=!1;a.j=document.createElement("gwd-image");a.h=document.createElement("gwd-image");a.f=document.createElement("gwd-image");a.m=document.createElement("gwd-page");a.o=a.A.bind(a);a.C=a.B.bind(a);a.g=!1;return a},F=HTMLElement;
E.prototype=e(F.prototype);E.prototype.constructor=E;if(n)n(E,F);else for(var G in F)if("prototype"!=G)if(Object.defineProperties){var H=Object.getOwnPropertyDescriptor(F,G);H&&Object.defineProperty(E,G,H)}else E[G]=F[G];
E.prototype.connectedCallback=function(){if(!this.g){for(var a;a=this.firstChild;)this.removeChild(a);this.a=document.createElement("div");this.a.className=this.c;this.appendChild(this.a);this.style.display="inline-block";this.style.padding=0;this.a.style.backgroundRepeat="no-repeat";this.a.style.width="100%";this.a.style.height="100%";this.g=!0;a=["bgcolor","alignment","scaling","disabled"];for(var b=0;b<a.length;b++){var c=a[b];this.attributeChangedCallback(c,null,this.getAttribute(c),null)}}this.a.addEventListener("click",
this.o,!1);this.gwdIsLoaded()||((a=t(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad())};E.prototype.disconnectedCallback=function(){this.a.removeEventListener("click",this.o,!1)};
E.prototype.attributeChangedCallback=function(a,b,c){if(this.g)switch(a){case "alignment":c?this.a.style.backgroundPosition=c:this.setAttribute(a,"center");break;case "scaling":c?this.a.style.backgroundSize=c:this.setAttribute(a,"auto");break;case "up-image":I(this,this.j,c||"");break;case "over-image":I(this,this.h,c||"");break;case "down-image":I(this,this.f,c||"");break;case "disabled":this.b=this.hasAttribute("disabled")&&"false"!=this.getAttribute("disabled");J(this);this.a.style.cursor=this.b?
"default":"pointer";break;case "bgcolor":this.a.style.backgroundColor=c&&!x(c)?c:""}};var I=function(a,b,c){x(c)?J(a):(b.setAttribute("source",c),a.g&&K(a))};E.prototype.gwdIsLoaded=function(){return this.s};E.prototype.gwdLoad=function(){K(this)};
var K=function(a,b,c,d){b=b?b:a.getAttribute("up-image");c=c?c:a.getAttribute("over-image");d=d?d:a.getAttribute("down-image");var f=document.createElement("gwd-page");f.style.display="none";var g=!1;g=u(a.j,b||"")||g;g=u(a.h,c||"")||g;if(g=u(a.f,d||"")||g)f.appendChild(a.j),f.appendChild(a.h),f.appendChild(a.f),a.m=f,w(f,"attached",f.gwdLoad.bind(f)),w(f,"pageload",a.C),a.a.appendChild(a.m)};
E.prototype.B=function(a){if(a){a=a.target;a===this.m&&(this.s=!0,J(this),v("ready",this),v("imagebuttonloaded",this));var b=a.parentNode||a.parentElement;b&&b.removeChild(a)}};E.prototype.A=function(a){this.b&&a.stopPropagation()};
var J=function(a){if(a.i){var b=a.i;(b=b.ownerNode||b.owningElement||b)&&b.parentNode&&b.parentNode.removeChild(b);a.i=null}b="";var c=a.j.getAttribute("source");x(c)||(b+="."+a.c+' { background-image: url("'+c+'"); }');a.b||(c=a.h.getAttribute("source"),x(c)||(b+="."+a.c+':hover { background-image: url("'+c+'"); }'),c=a.f.getAttribute("source"),x(c)||(b+="."+a.c+':active { background-image: url("'+c+'"); }'));var d=document;c=d.getElementsByTagName("head")[0];if(!c){var f=d.getElementsByTagName("body")[0];
c=d.createElement("head");f.parentNode.insertBefore(c,f)}d=d.createElement("style");d.textContent=b;c.appendChild(d);a.i=d};E.prototype.toggleEnable=function(){(this.b=!this.b)?this.setAttribute("disabled","true"):this.removeAttribute("disabled")};E.prototype.setImages=function(a,b,c){K(this,a,b,c)};q.Object.defineProperties(E,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return B}}});customElements.define("gwd-imagebutton",E);}).call(this);
