(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g,k="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},m;if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var p={K:!0},q={};try{q.__proto__=p;n=q.K;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var r=m,t=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},u=t(this),goog=goog||{},v=this||self,w=Date.now||function(){return+new Date},x=function(a,b){a=a.split(".");var c=v;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||
void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};var y=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d)},z=function(a,b,c){var d=function(e){a.removeEventListener(b,d);c(e)};a.addEventListener(b,d)};var A="center top bottom left right transparent".split(" ");var B=["-ms-","-moz-","-webkit-",""],C=function(a,b){var c=void 0===c?!1:c;for(var d,e,f=0;f<B.length;f++)d=B[f]+"transition-duration",e=(c?B[f]:"")+b,a.style.setProperty(d,e)},D=function(a){var b=document,c=b.getElementsByTagName("head")[0];if(!c){var d=b.getElementsByTagName("body")[0];c=b.createElement("head");d.parentNode.insertBefore(c,d)}b=b.createElement("style");b.textContent=a;c.appendChild(b);return b};var E=function(a){for(var b=0;b<A.length;b++)a.classList.remove(A[b])},F=function(a,b){var c=function(){a.removeEventListener("webkitTransitionEnd",c);a.removeEventListener("transitionend",c);b()};a.addEventListener("webkitTransitionEnd",c);a.addEventListener("transitionend",c)},G=function(a,b,c,d){c="transform: matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,"+c+","+d+",0,1);";return a+"."+b+"{-webkit-"+c+"-moz-"+c+"-ms-"+c+c+"}"},H=function(a,b,c){a=(a&&"#")+a+".gwd-pagedeck > .gwd-page";return G(a,"center",0,
0)+G(a,"top",0,c)+G(a,"bottom",0,-c)+G(a,"left",b,0)+G(a,"right",-b,0)},I=function(a,b,c,d,e,f,h){d=void 0===d?"none":d;this.b=a;this.c=b;this.B=c;this.i="none"==d?0:void 0===e?1E3:e;this.j=void 0===f?"linear":f;this.m=[];if(this.i){a=d;h=void 0===h?"top":h;if(this.b){this.b.classList.add("gwd-page");this.b.classList.add("center");b="center";if("push"==a)switch(h){case "top":b="top";break;case "bottom":b="bottom";break;case "left":b="left";break;case "right":b="right"}this.m.push(b);"fade"==a&&this.m.push("transparent")}b=
"center";if("none"!=a&&"fade"!=a)switch(h){case "top":b="bottom";break;case "bottom":b="top";break;case "left":b="right";break;case "right":b="left"}this.c.classList.add(b);this.c.classList.add("gwd-page");"fade"==a&&this.c.classList.add("transparent")}};
I.prototype.start=function(){if(this.i){F(this.c,this.S.bind(this));this.b&&(C(this.b,this.i+"ms"),this.b.classList.add(this.j));C(this.c,this.i+"ms");this.c.classList.add(this.j);var a=this.c;a.setAttribute("gwd-reflow",a.offsetWidth);if(this.b)for(a=0;a<this.m.length;a++)this.b.classList.add(this.m[a]);E(this.c)}else this.B()};I.prototype.S=function(){this.b&&(E(this.b),C(this.b,0),this.b.classList.remove(this.j));C(this.c,0);this.c.classList.remove(this.j);this.B()};var J=function(){this.G=""};J.prototype.toString=function(){return"SafeScript{"+this.G+"}"};J.prototype.g=function(a){this.G=a};(new J).g("");var K=function(){this.I=""};K.prototype.toString=function(){return"SafeStyle{"+this.I+"}"};K.prototype.g=function(a){this.I=a};(new K).g("");var L=function(){this.H=""};L.prototype.toString=function(){return"SafeStyleSheet{"+this.H+"}"};L.prototype.g=function(a){this.H=a};(new L).g("");var M=function(){this.F=""};M.prototype.toString=function(){return"SafeHtml{"+this.F+"}"};M.prototype.g=function(a){this.F=a};(new M).g("<!DOCTYPE html>");(new M).g("");(new M).g("<br>");Object.freeze&&Object.freeze([]);var N=function(a,b){var c=(c=v.performance)&&c.now&&c.timing?Math.floor(c.now()+c.timing.navigationStart):w();a={label:a,type:9,value:c};b=b.google_js_reporting_queue=b.google_js_reporting_queue||[];2048>b.length&&b.push(a)};var P={},Q=!1,R=!1;P.P=function(a){Q||(Q=!0,N("11",a))};P.A=function(a){R||(R=!0,N("12",a))};P.R=function(a,b,c){var d=b;d=void 0===d?v:d;if(d=(d=d.performance)&&d.now?d.now():null)a={label:a,type:void 0===c?0:c,value:d},b=b.google_js_reporting_queue=b.google_js_reporting_queue||[],2048>b.length&&b.push(a)};P.reset=function(a){R=Q=!1;(a.google_js_reporting_queue=a.google_js_reporting_queue||[]).length=0};x("gwd.rumUtil",P);x("gwd.rumUtil.logContentLoading",P.P);
x("gwd.rumUtil.logContentRendered",P.A);x("gwd.rumUtil.logTimingEvent",P.R);x("gwd.rumUtil.reset",P.reset);var S=function(){var a=HTMLElement.call(this)||this;z(window,"WebComponentsReady",a.O.bind(a));a.v=a.l.bind(a,"shake");a.w=a.l.bind(a,"tilt");a.u=a.l.bind(a,"rotatetoportrait");a.s=a.l.bind(a,"rotatetolandscape");a.a=[];a.C=a.N.bind(a);a.L=a.M.bind(a);a.D=null;a.h=null;a.f=-1;a.o=!1;return a},T=HTMLElement;S.prototype=k(T.prototype);S.prototype.constructor=S;
if(r)r(S,T);else for(var U in T)if("prototype"!=U)if(Object.defineProperties){var V=Object.getOwnPropertyDescriptor(T,U);V&&Object.defineProperty(S,U,V)}else S[U]=T[U];S.prototype.connectedCallback=function(){this.addEventListener("pageload",this.C,!1);document.body.addEventListener("shake",this.v,!0);document.body.addEventListener("tilt",this.w,!0);document.body.addEventListener("rotatetoportrait",this.u,!0);document.body.addEventListener("rotatetolandscape",this.s,!0)};
S.prototype.disconnectedCallback=function(){this.removeEventListener("pageload",this.C,!1);document.body&&(document.body.removeEventListener("shake",this.v,!0),document.body.removeEventListener("tilt",this.w,!0),document.body.removeEventListener("rotatetoportrait",this.u,!0),document.body.removeEventListener("rotatetolandscape",this.s,!0))};
S.prototype.O=function(){this.classList.add("gwd-pagedeck");this.D||(this.D=D(H(this.id,this.offsetWidth,this.offsetHeight)));this.a=Array.prototype.slice.call(this.querySelectorAll("gwd-page"));this.a.forEach(function(a){a.classList.add("gwd-page")});for(y("beforepagesdetached",this,{pages:this.a.slice()});this.firstChild;)this.removeChild(this.firstChild);-1==this.f&&void 0!==this.J&&this.goToPage(this.J)};
var X=function(a,b,c,d,e,f){if(!(a.f==b||0>b||b>a.a.length-1||a.h)){var h=a.a[a.f],l=a.a[b];a.f=b;a.h=new I(h,l,a.L,c,d,e,f);var O=l.gwdLoad&&!l.gwdIsLoaded();a.o=O;z(l,"attached",function(){l.gwdActivate();O?l.gwdLoad():W(a)});a.appendChild(l)}};S.prototype.N=function(a){this.o&&a.target.parentNode==this&&(W(this),this.o=!1)};var W=function(a){(0,P.A)(window);a.h.start();y("pagetransitionstart",a)};g=S.prototype;
g.M=function(){if(this.h){var a=this.h.b,b=this.h.c;this.h=null;y("pagetransitionend",this,{outgoingPage:a?a:null,incomingPage:b});a&&a.gwdDeactivate();b.gwdPresent()}};g.findPageIndexByAttributeValue=function(a,b){for(var c=this.a.length,d,e=0;e<c;e++)if(d=this.a[e],"boolean"==typeof b){if(d.hasAttribute(a))return e}else if(d.getAttribute(a)==b)return e;return-1};g.goToNextPage=function(a,b,c,d,e){var f=this.f,h=f+1;h>=this.a.length&&(h=a?0:f);X(this,h,b,c,d,e)};
g.goToPreviousPage=function(a,b,c,d,e){var f=this.f,h=this.a.length,l=f-1;0>l&&(l=a?h-1:f);X(this,l,b,c,d,e)};g.goToPage=function(a,b,c,d,e){this.a.length?(a="number"==typeof a?a:this.findPageIndexByAttributeValue("id",a),0<=a&&X(this,a,b,c,d,e)):this.J=a};g.getPages=function(){return this.a};g.getPage=function(a){if("number"!=typeof a){if(!a)return null;a=this.findPageIndexByAttributeValue("id",a)}return 0>a||a>this.a.length-1?null:this.a[a]};g.getCurrentPage=function(){return this.getPage(this.f)};
g.getDefaultPage=function(){var a=this.getAttribute("default-page");return a?this.getPage(this.findPageIndexByAttributeValue("id",a)):this.getPage(0)};g.getOrientationSpecificPage=function(a,b){b=this.getPage(b);var c=b.getAttribute("alt-orientation-page");if(!c)return b;var d=b.isPortrait();a=1==a;c=this.getPage(c);return a==d?b:c};g.l=function(a,b){if(b.target==document.body){var c=this.getPage(this.f);y(a,c,b.detail)}};
g.getElementById=function(a){for(var b=this.a.length,c=0;c<b;c++){var d=this.a[c].querySelector("#"+a);if(d)return d}return null};g.getElementsBySelector=function(a){for(var b=this.a.length,c=[],d=0;d<b;d++){var e=this.a[d].querySelectorAll(a);e&&(c=c.concat(Array.prototype.slice.call(e)))}return c};u.Object.defineProperties(S.prototype,{currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<=this.f?this.f:void 0}}});customElements.define("gwd-pagedeck",S);}).call(this);
