(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e,f="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var l={D:!0},m={};try{m.__proto__=l;h=m.D;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var n=g,p=this||self,q=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},r=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};var t=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d};var u=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,u);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};r(u,Error);u.prototype.name="CustomError";var v=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,k=0;k<d;k++)c+=a[k]+(k<b.length?b[k]:"%s");u.call(this,c+a[d])};r(v,u);v.prototype.name="AssertionError";var w=function(a,b,c){if(!a){var d="Assertion failed";if(b){d+=": "+b;var k=Array.prototype.slice.call(arguments,2)}throw new v(""+d,k||[]);}return a},x=function(a,b){throw new v("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var y=function(){this.j=""};y.prototype.c=!0;y.prototype.b=function(){return this.j.toString()};y.prototype.toString=function(){return"SafeScript{"+this.j+"}"};y.prototype.a=function(a){this.j=a};(new y).a("");var B=function(a,b){this.o=a===z&&b||"";this.C=A};B.prototype.c=!0;B.prototype.b=function(){return this.o.toString()};B.prototype.toString=function(){return"SafeUrl{"+this.o+"}"};var C=function(a){if(a instanceof B&&a.constructor===B&&a.C===A)return a.o;x("expected object of type SafeUrl, got '"+a+"' of type "+q(a));return"type_error:SafeUrl"},D=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,A={},z={};var E=function(){this.m=""};E.prototype.c=!0;E.prototype.b=function(){return this.m};E.prototype.toString=function(){return"SafeStyle{"+this.m+"}"};E.prototype.a=function(a){this.m=a};(new E).a("");var F=function(){this.l=""};F.prototype.c=!0;F.prototype.b=function(){return this.l};F.prototype.toString=function(){return"SafeStyleSheet{"+this.l+"}"};F.prototype.a=function(a){this.l=a};(new F).a("");var G=function(){this.i=""};G.prototype.c=!0;G.prototype.b=function(){return this.i.toString()};G.prototype.toString=function(){return"SafeHtml{"+this.i+"}"};G.prototype.a=function(a){this.i=a};(new G).a("<!DOCTYPE html>");(new G).a("");(new G).a("<br>");var H=[],I=function(a){a=H.indexOf(a);0<=a&&H.splice(a,1)};document.addEventListener("click",function(a){for(var b=0;b<H.length;b++)if(25>Math.abs(a.clientX-H[b].F)&&25>Math.abs(a.clientY-H[b].G)||25>Math.abs(a.screenX-H[b].L)&&25>Math.abs(a.screenY-H[b].M))H.splice(b,1),a.stopPropagation(),a.preventDefault()},!0);var J=function(){var a=HTMLElement.call(this)||this;a.A=0;a.B=0;a.h=null;a.u=null;a.g=null;a.s=null;a.v=a.H.bind(a);a.f=!0;return a},K=HTMLElement;J.prototype=f(K.prototype);
J.prototype.constructor=J;if(n)n(J,K);else for(var L in K)if("prototype"!=L)if(Object.defineProperties){var M=Object.getOwnPropertyDescriptor(K,L);M&&Object.defineProperty(J,L,M)}else J[L]=K[L];e=J.prototype;e.connectedCallback=function(){this.g||(this.h=this.w.bind(this),this.u=this.K.bind(this),this.g=this.J.bind(this),this.s=this.I.bind(this));this.addEventListener("click",this.h,!1);this.addEventListener("touchstart",this.u,!1);this.addEventListener("action",this.v,!1)};
e.disconnectedCallback=function(){this.removeEventListener("click",this.h,!1);this.removeEventListener("touchstart",this.u,!1);this.removeEventListener("action",this.v,!1)};e.w=function(a){this.f&&t("action",this,a);this.f=!0};e.K=function(a){this.addEventListener("touchmove",this.g,!1);this.addEventListener("touchend",this.s,!1);a=a.touches[0];this.A=a.clientX;this.B=a.clientY};
e.I=function(a){this.w(a);this.removeEventListener("touchmove",this.g,!1);this.removeEventListener("touchend",this.s,!1);a=a.changedTouches[0];a={F:a.clientX,G:a.clientY,L:a.screenX,M:a.screenY};H.push(a);setTimeout(I.bind(null,a),2500)};e.J=function(a){a=a.touches[0];this.f=this.f&&10>=Math.abs(this.A-a.clientX)&&10>=Math.abs(this.B-a.clientY)};
e.H=function(a){var b=this.getAttribute("exit-id"),c=this.getAttribute("product-index"),d=this.getAttribute("exit-override-url");d&&!t("tapareaexit",this,{"exit-id":b,url:d,"product-index":c,"action-event":a.detail}).detail.handled&&(d instanceof B?a=d:(a=d,a instanceof B||(a="object"==typeof a&&a.c?a.b():String(a),w(D.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new B(z,a))),p.open(C(a),"",void 0,void 0))};customElements.define("gwd-taparea",J);}).call(this);
