(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},g;if("function"==typeof Object.setPrototypeOf)g=Object.setPrototypeOf;else{var h;a:{var k={A:!0},l={};try{l.__proto__=k;h=l.A;break a}catch(a){}h=!1}g=h?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var m=g,goog=goog||{},n=this||self,p=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},q=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};var r=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,r);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};q(r,Error);r.prototype.name="CustomError";var t=function(a,b){a=a.split("%s");for(var c="",e=a.length-1,f=0;f<e;f++)c+=a[f]+(f<b.length?b[f]:"%s");r.call(this,c+a[e])};q(t,r);t.prototype.name="AssertionError";var u=function(a,b,c){if(!a){var e="Assertion failed";if(b){e+=": "+b;var f=Array.prototype.slice.call(arguments,2)}throw new t(""+e,f||[]);}return a},v=function(a,b){throw new t("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var y=function(a,b){this.m=a===w&&b||"";this.w=x};y.prototype.f=!0;y.prototype.c=function(){return this.m};y.prototype.toString=function(){return"Const{"+this.m+"}"};var x={},w={};var z=new y(w,"_newtab");var A=function(){this.h=""};A.prototype.f=!0;A.prototype.c=function(){return this.h.toString()};A.prototype.toString=function(){return"SafeScript{"+this.h+"}"};A.prototype.a=function(a){this.h=a};(new A).a("");var D=function(a,b){this.l=a===B&&b||"";this.v=C};D.prototype.f=!0;D.prototype.c=function(){return this.l.toString()};D.prototype.toString=function(){return"SafeUrl{"+this.l+"}"};var E=function(a){if(a instanceof D&&a.constructor===D&&a.v===C)return a.l;v("expected object of type SafeUrl, got '"+a+"' of type "+p(a));return"type_error:SafeUrl"},F=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,C={},B={};var G=function(){this.j=""};G.prototype.f=!0;G.prototype.c=function(){return this.j};G.prototype.toString=function(){return"SafeStyle{"+this.j+"}"};G.prototype.a=function(a){this.j=a};(new G).a("");var H=function(){this.i=""};H.prototype.f=!0;H.prototype.c=function(){return this.i};H.prototype.toString=function(){return"SafeStyleSheet{"+this.i+"}"};H.prototype.a=function(a){this.i=a};(new H).a("");var I=function(){this.g=""};I.prototype.f=!0;I.prototype.c=function(){return this.g.toString()};I.prototype.toString=function(){return"SafeHtml{"+this.g+"}"};I.prototype.a=function(a){this.g=a};(new I).a("<!DOCTYPE html>");(new I).a("");(new I).a("<br>");var J=function(){var a=HTMLElement.call(this)||this;a.o=!1;a.u=a.B.bind(a);a.s=null;return a},K=HTMLElement;J.prototype=d(K.prototype);J.prototype.constructor=J;if(m)m(J,K);else for(var L in K)if("prototype"!=L)if(Object.defineProperties){var M=Object.getOwnPropertyDescriptor(K,L);M&&Object.defineProperty(J,L,M)}else J[L]=K[L];
J.prototype.connectedCallback=function(){var a=this;this.o||(document.body.style.opacity="0");setTimeout(function(){a.b=a.querySelector("gwd-pagedeck");window.addEventListener("resize",a.u,!1)},0)};J.prototype.disconnectedCallback=function(){window.removeEventListener("resize",this.u,!1)};J.prototype.initAd=function(){this.o=!0;document.body.style.opacity="";var a=void 0===a?null:a;var b=document.createEvent("CustomEvent");b.initCustomEvent("adinitialized",!0,!0,a);this.dispatchEvent(b);this.goToPage()};
J.prototype.goToPage=function(a,b,c,e,f){if(a=void 0!=a?this.b.getPage(a):this.b.getDefaultPage())a=this.b.getOrientationSpecificPage(window.innerHeight>=window.innerWidth?1:2,a.id),void 0!=b?this.b.goToPage(a.id,b,c,e,f):this.b.goToPage(a.id)};J.prototype.B=function(){var a=window.innerHeight>=window.innerWidth?1:2;this.s!=a&&(this.s=a,(a=this.b.getPage(Number(this.b.currentIndex)))&&this.goToPage(a.id))};
J.prototype.exit=function(a,b,c){b=void 0===b?!1:b;a instanceof D||a instanceof D||(a="object"==typeof a&&a.f?a.c():String(a),u(F.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new D(B,a));if(z instanceof y)if(z instanceof y&&z.constructor===y&&z.w===x)var e=z.m;else v("expected object of type Const, got '"+z+"'"),e="type_error:Const";else e=z||"";n.open(E(a),e,void 0,void 0);b&&this.goToPage(c)};customElements.define("gwd-genericad",J);}).call(this);
