({name:"adtlgcen_Cookie",set:function(a,b,c){this.shouldSendSameSiteNone()?this.setSecure(a,b,c):this.setNonSecure(a,b,c)},setNonSecure:function(a,b,c){var d=new Date;c&&d.setTime(d.getTime()+36E5*c);c="; expires="+d.toGMTString();document.cookie=escape(a)+"="+b+c+"; path=/"},setSecure:function(a,b,c){var d=new Date;c&&d.setTime(d.getTime()+36E5*c);c="; expires="+d.toGMTString();document.cookie=escape(a)+"="+b+c+"; path=/; SameSite=None; Secure"},get:function(a){var b=document.cookie;var c=a+"=";
var d=b.indexOf("; "+c);if(-1==d){if(d=b.indexOf(c),0!==d)return""}else d+=2;a=b.indexOf(";",d);-1==a&&(a=b.length);return unescape(b.substring(d+c.length,a))},unset:function(a){return this.set(a,"")},init:function(){window[this.name]=this},shouldSendSameSiteNone:function(){return!this.isSameSiteNoneIncompatible(navigator.userAgent)},isSameSiteNoneIncompatible:function(a){return this.hasWebKitSameSiteBug(a)||this.dropsUnrecognizedSameSiteCookies(a)},hasWebKitSameSiteBug:function(a){return this.isIosVersion(12,
a)||this.isMacosxVersion(10,14,a)&&(this.isSafari(a)||this.isMacEmbeddedBrowser(a))},dropsUnrecognizedSameSiteCookies:function(a){return this.isUcBrowser(a)?!this.isUcBrowserVersionAtLeast(12,13,2,a):this.isChromiumBased(a)&&this.isChromiumVersionAtLeast(51,a)&&!this.isChromiumVersionAtLeast(67,a)},isIosVersion:function(a,b){return(b=b.match(/iP.+;\sCPU\s.*OS\s(\d+)[_\d]*.*AppleWebKit/i))&&b[1]==a},isMacosxVersion:function(a,b,c){return(c=c.match(/Macintosh;\s.*Mac\sOS\sX\s(\d+)_(\d+)[_\d+]*.*AppleWebKit/i))&&
2<c.length&&c[1]==a&&c[2]==b},isSafari:function(a){return a.match(/Version.*Safari/i)&&!isChromiumBased(a)},isMacEmbeddedBrowser:function(a){return(a=a.match(/^Mozilla\/[\.\d]+.*\(Macintosh;.*Mac OS X\s*[_\d]?.*\) AppleWebKit\/[\.\d]+.*\(KHTML, like Gecko.*\)/i))&&0<a.length},isChromiumBased:function(a){return(a=a.match(/Chrom[[e|ium]+/i))&&0<a.length},isChromiumVersionAtLeast:function(a,b){return(b=b.match(/Chrom[^ \/]+\/(\d+)[\.\d]*/i))&&0<b.length&&b[0]>=a},isUcBrowser:function(a){return(a=a.match(/UCBrowser/i))&&
0<a.length},isUcBrowserVersionAtLeast:function(a,b,c,d){var e=d.match(/UCBrowser\/(\d+)\.(\d+)\.(\d+)[\.\d]*/i);if(e&&4<=e.length){d=parseInt(e[1]);var f=parseInt(e[2]),e=parseInt(e[3]);return d!=a?d>a:f!=b?f>b:e>=c}}}).init();var cX=cX||{};cX.callQueue=cX.callQueue||[];
if(!window.admp_){var DataRequest=function(a){this.fn=a;this.send=function(a,c){if(c||adtlgcen.util.validateEvIdCookie(enr_vars.evid))a+="&evid="+window[enr_vars.evid];a+=adtlgcen_SETTINGS.SCRIPT_VERSION_PARAMETER;c=document.createElement("script");c.setAttribute("type","text/javascript");c.setAttribute("charset","utf-8");c.setAttribute("src",a);document.getElementsByTagName("head")[0].appendChild(c)};this.campaignCallback=function(a){a&&"-entered"!=a.evId&&(adtlgcen_Cookie.set(enr_vars.evid,a.evId,
2160),a.vv&&adtlgcen_Cookie.set(enr_vars.evid_v,a.vv,2160));if(adtlgcen.util.validateEvIdCookie(enr_vars.evid)){adtlgcen_Cookie.set(enr_vars.adptset,"1",2);window[enr_vars.evid]=adtlgcen_Cookie.get(enr_vars.evid);window[enr_vars.evid_v]=adtlgcen_Cookie.get(enr_vars.evid_v);if(a=a.segments){for(var c="",b=0;b<a.length;b++)a[b]&&(c&&(c+=";"),c+=a[b]);c&&adtlgcen_Cookie.set(enr_vars.adptseg,c.replace(/;/g,"-").replace(/=/g,"#"),2)}adtlgcen.util.makePageImpCall()}else a=adtlgcen_SETTINGS.TC_URL+"/validate?callback="+
enr_vars.dataRequest+".validateCallback&cb="+(new Date).getTime(),this.send(a)};this.validateCallback=function(a){a&&(adtlgcen_Cookie.set(enr_vars.evid,a.evId,2160),a.vv&&adtlgcen_Cookie.set(enr_vars.evid_v,a.vv,2160),window[enr_vars.evid]=adtlgcen_Cookie.get(enr_vars.evid),window[enr_vars.evid_v]=adtlgcen_Cookie.get(enr_vars.evid_v),adtlgcen_Cookie.set(enr_vars.adptset,"1",2),adtlgcen_Cookie.set(enr_vars.evid_set,2,1/60),adtlgcen.util.makePageImpCall())}};try{window.loc_="undefined"==window.location.href&&
JSON&&JSON.parse&&JSON.stringify?JSON.parse(JSON.stringify(window.location)):window.location}catch(a){window.loc_=window.location}window.loc_.origin||(window.loc_.origin=window.loc_.protocol+"//"+window.loc_.hostname+(window.loc_.port?":"+window.loc_.port:""));window.adtlgcen=window.adtlgcen||{};adtlgcen.config=adtlgcen.config||{};adtlgcen.util=adtlgcen.util||{};var adtlgcen_SETTINGS={TC_URL:window.loc_.protocol+"//admp-tc-pmp.adtlgc.com",SCRIPT_VERSION_PARAMETER:"&v=2.37",CINT_URL:"https://collector.cint.com?a=2495&i=47&id=evid_0047:"},
enr_vars={evid:"evid_0047",evid_v:"evid_v_0047",evid_set:"evid_set_0047",adptseg:"adptseg_0047",adptset:"adptset_0047",dataRequest:"adapt_dataRequest_pmp_admp",persistedUpdateQueryId:"4f29744b04a0cc76fa6e54c929c437b78469e838",persistedLinkQueryId:"714257a463ca162aa7fb3f92965ed889d83e0255",gig_persistedLinkQueryId:"6e5a68549a550479d2d6a698de4fd03107e8f0a7",cxPrefixes:["pmp"]},segmentGroups={kv1001:"-ecsegm-gender",kv1002:"-ecsegm-age",kv1003:"-ecsegm-education",kv1004:"-ecsegm-income",kv1005:"-ecsegm-employment",
kv1006:"-ecsegm-childrencount",kv1007:"-ecsegm-householdsize",kv1009:"-ecsegm-interests"},segmentValues={"kv1001=a":"male","kv1001=b":"female","kv1002=a":"under18","kv1002=b":"18-24","kv1002=c":"25-34","kv1002=d":"35-44","kv1002=e":"45-54","kv1002=f":"55-64","kv1002=g":"over65","kv1003=a":"PrimarySecondarySchool","kv1003=b":"HighSchoolTertiaryTechCollege","kv1003=c":"UniversityPostgraduate","kv1003=d":"EducationLevelOther","kv1004=a":"Less than \u20ac12 000","kv1004=b":"\u20ac12 000 - \u20ac20 000",
"kv1004=c":"\u20ac20 000 - \u20ac45 000","kv1004=d":"\u20ac45 000 - \u20ac70 000","kv1004=e":"More than \u20ac70 000","kv1005=a":"studying","kv1005=b":"working","kv1005=c":"other","kv1006=a":"1","kv1006=b":"2-3","kv1006=c":"4 and more","kv1006=d":"none","kv1007=a":"1","kv1007=b":"2-4","kv1007=c":"5more","kv1009=1":"Animal Lovers","kv1009=10":"Designer Fashion & Beauty","kv1009=11":"Food, Wine & Dining","kv1009=12":"Technology & Gadgets","kv1009=13":"Gaming","kv1009=14":"Plants & Gardening","kv1009=15":"Health, Fitness & Wellbeing",
"kv1009=16":"Music Lovers","kv1009=17":"Weekends & Nightlife","kv1009=18":"Children & Parenting","kv1009=19":"Video Imaging & Photos","kv1009=2":"Interior Design & Furnishing","kv1009=20":"Science & Discovery","kv1009=21":"Training & Exercise","kv1009=22":"Sports Followers","kv1009=23":"Style & Trend Setters","kv1009=24":"World Travel Enthusiasts","kv1009=25":"Home Improvement & DIY","kv1009=26":"Extreme Sports","kv1009=3":"Racing & Automotive Enthusiasts","kv1009=4":"Active Outdoors & Nature","kv1009=5":"Personal Finance & Economy",
"kv1009=6":"Business & Career","kv1009=7":"Theater, Arts & Culture","kv1009=8":"Organic & Sustainable Development","kv1009=9":"Celebrities & Entertainment"};adtlgcen.util.isContent=function(){var a=0<document.getElementsByTagName("bi3dtext").length;if(!a)for(var b=document.getElementsByTagName("*"),c=0,d=b.length;c<d;c++)if(attr=b[c].getAttribute("itemtype"))if("http://schema.org/NewsArticle"==attr||"http://schema.org/Article"==attr){a=!0;break}return a};adtlgcen.util.localStorageEnabled=function(){try{return"object"===
typeof window.localStorage&&"function"===typeof window.localStorage.getItem}catch(a){return!1}};adtlgcen.util.isSafari=function(){try{return!(!(navigator.userAgent.match(/Safari/)||navigator.userAgent.match(/iPad/)||navigator.userAgent.match(/iPhone/))||navigator.userAgent.match(/Chrome|bot|link/))}catch(a){return!1}};adtlgcen.util.send=function(a,b,c){b||(a+="&evid="+window[enr_vars.evid],window[enr_vars.evid_v]&&(a+="&vv="+window[enr_vars.evid_v]),a+=adtlgcen_SETTINGS.SCRIPT_VERSION_PARAMETER);
if(c)setTimeout(function(){(new Image(0,0)).src=a},100);else if(-1!=navigator.appVersion.indexOf("MSIE")&&8>parseFloat(navigator.appVersion.split("MSIE")[1]))setTimeout(function(){(new Image(0,0)).src=a},1E3);else{(b=!1,"undefined"==typeof XDomainRequest)||(b=new XDomainRequest);if(!b&&"undefined"!=typeof XMLHttpRequest)try{b=new XMLHttpRequest}catch(d){b=!1}if(!b&&window.createRequest)try{b=window.createRequest()}catch(d){b=!1}b&&(b.open("GET",a,!0),b.send(""));return b}};adtlgcen.util.validateEvIdCookie=
function(a){return adtlgcen_Cookie.get(a)&&"-entered"!=adtlgcen_Cookie.get(a)};adtlgcen.util.en_smart_decode=function(a){a=a.split("%");for(var b=a[0],c=1;c<a.length;c++){try{if(2==a[c].length&&a.length>c&&2<=a[c+1].length)try{b+=decodeURIComponent("%"+a[c]+"%"+a[c+1].substring(0,2));b+=a[c+1].substring(2,a[c+1].length);c++;continue}catch(d){}if(2<=a[c].length){b+=decodeURIComponent("%"+a[c].substring(0,2))+a[c].substring(2,a[c].length);continue}}catch(d){}b+="%"+a[c]}return b};adtlgcen.util.makePageImpCall=
function(){if("optout"!=window[enr_vars.evid]){var a=adtlgcen_SETTINGS.TC_URL+"/event/v3/pagestat?location="+(encodeURIComponent||escape)(window.loc_.href)+(adtlgcen.util.isContent()?"&isContent=1":"")+"&cb="+(new Date).getTime();adtlgcen.util.send(a);a=adtlgcen.util.en_smart_decode(window.loc_.href);a=adtlgcen_SETTINGS.TC_URL+"/event/v3/arstat?location="+(encodeURIComponent||escape)(a)+"&cb="+(new Date).getTime();adtlgcen.util.send(a);if(adtlgcen.util.validateEvIdCookie(enr_vars.evid)){var b=adtlgcen_Cookie.get(enr_vars.adptseg).replace(/-/g,
"|").split("|");cX.callQueue.push(["invoke",function(){for(var a=[],b=0;b<enr_vars.cxPrefixes.length;b++)a[a.length]={id:adtlgcen_Cookie.get(enr_vars.evid),cxid:cX.getUserId()};a=cX.getCookie("gig_cxenseID");"undefined"!==typeof a&&null!==a&&"undefined"!==a&&0<a.toString().length&&(a={id:a,cxid:cX.getUserId()},a="https://api.cxense.com/profile/user/external/link/update?callback={{callback}}&persisted="+encodeURIComponent(enr_vars.gig_persistedLinkQueryId)+"&json="+encodeURIComponent(cX.JSON.stringify(a)),
cX.jsonpRequest(a,function(a){}))}]);b&&0<b.length&&b[0]&&cX.callQueue.push(["invoke",function(){if(!cX.getCookie("enr_cxense_throttle")){for(var a=[],d=0;d<enr_vars.cxPrefixes.length;d++){for(var e=enr_vars.cxPrefixes[d],f=[],g=0;g<b.length;g++){var h=b[g].split("#");if(segmentGroups[h[0]]){var k=segmentValues[b[g].replace("#","=")];k&&(f[f.length]={item:k,group:e+segmentGroups[h[0]]})}}0<f.length&&(a[a.length]={id:adtlgcen_Cookie.get(enr_vars.evid),cxid:cX.getUserId(),profile:f})}0<a.length&&(a=
"https://api.cxense.com/profile/user/external/update?callback={{callback}}&persisted="+encodeURIComponent(enr_vars.persistedUpdateQueryId)+"&json="+encodeURIComponent(cX.JSON.stringify(a)),cX.jsonpRequest(a,function(a){}),cX.setCookie("enr_cxense_throttle","throttle",7))}}])}adtlgcen.util.validateEvIdCookie(enr_vars.evid)&&"1"!=adtlgcen_Cookie.get("enr_cint_sent")&&(adtlgcen.util.send(adtlgcen_SETTINGS.CINT_URL+window[enr_vars.evid],!0,!0),adtlgcen_Cookie.set("enr_cint_sent","1",24))}};window.admp_=
new function(){};adtlgcen.util.getUserId=function(){adtlgcen.util.createSyncIFrame("enGlobalIframe",window.loc_.protocol+"//code3.adtlgc.com/js/global.html",function(){var a={action:"getUser",origin:window.loc_.origin};a.enr_vars=enr_vars;a.enr_settings=adtlgcen_SETTINGS;document.getElementById("enGlobalIframe").contentWindow.postMessage(JSON.stringify(a),window.loc_.protocol+"//code3.adtlgc.com")})};adtlgcen.util.createSyncIFrame=function(a,b,c){if(document.body){var d=document.createElement("iframe");
c&&(d.addEventListener?d.addEventListener("load",c,!0):d.attachEvent&&d.attachEvent("onload",c));a&&(d.id=a,d.name=a);d.width=0;d.height=0;d.scrolling="no";d.frameBorder=0;d.src=b;d.style.display="none";document.body.appendChild(d);return d}setTimeout(function(){adtlgcen.util.createSyncIFrame(a,b,c)},200)};adtlgcen.util.optOut=function(){adtlgcen_Cookie.set(enr_vars.evid,"optout",2160);adtlgcen_Cookie.unset(enr_vars.evid_v);adtlgcen_Cookie.unset(enr_vars.adptseg);adtlgcen_Cookie.unset(enr_vars.adptset);
window[enr_vars.evid]="optout";adtlgcen.util.createSyncIFrame("enGlobalIframe",window.loc_.protocol+"//code3.adtlgc.com/js/global.html",function(){var a={action:"optOut",origin:window.loc_.origin};a.enr_vars=enr_vars;a.enr_settings=adtlgcen_SETTINGS;document.getElementById("enGlobalIframe").contentWindow.postMessage(JSON.stringify(a),window.loc_.protocol+"//code3.adtlgc.com")});var a=adtlgcen_SETTINGS.TC_URL+"/getCampaigns.do?includeSegments=false&cb="+(new Date).getTime();window[enr_vars.dataRequest].send(a,
!0)};adtlgcen.util.optIn=function(){adtlgcen_Cookie.unset(enr_vars.evid);adtlgcen_Cookie.unset(enr_vars.adptset);window[enr_vars.evid]="-entered";adtlgcen.util.createSyncIFrame("enGlobalIframe",window.loc_.protocol+"//code3.adtlgc.com/js/global.html",function(){var a={action:"optIn",origin:window.loc_.origin};a.enr_vars=enr_vars;a.enr_settings=adtlgcen_SETTINGS;document.getElementById("enGlobalIframe").contentWindow.postMessage(JSON.stringify(a),window.loc_.protocol+"//code3.adtlgc.com")});var a=
adtlgcen_SETTINGS.TC_URL+"/getCampaigns.do?includeSegments=false&callback="+enr_vars.dataRequest+".campaignCallback&cb="+(new Date).getTime();window[enr_vars.dataRequest].send(a,!0)};admp_.init=function(){function a(){if("1"!=adtlgcen_Cookie.get(enr_vars.adptset))if("optout"!=window[enr_vars.evid]){adtlgcen_Cookie.set(enr_vars.evid_set,1,1/60);var a=adtlgcen_SETTINGS.TC_URL+"/getCampaigns.do?includeSegments=true&callback="+enr_vars.dataRequest+".campaignCallback&cb="+(new Date).getTime();window[enr_vars.dataRequest].send(a)}else adtlgcen_Cookie.set(enr_vars.adptset,
"1",2),adtlgcen.util.makePageImpCall();else adtlgcen.util.makePageImpCall();adtlgcen.util.validateEvIdCookie(enr_vars.evid)&&adtlgcen_Cookie.set(enr_vars.evid_set,2,1/60)}window[enr_vars.evid]=adtlgcen_Cookie.get(enr_vars.evid);window[enr_vars.evid_v]=adtlgcen_Cookie.get(enr_vars.evid_v);window[enr_vars.evid]&&0==window[enr_vars.evid].indexOf("cx:")&&(window[enr_vars.evid]=window[enr_vars.evid].replace(/:/g,"-"),adtlgcen_Cookie.set(enr_vars.evid,window[enr_vars.evid],2160),adtlgcen_Cookie.unset(enr_vars.adptset));
if(adtlgcen.util.localStorageEnabled())try{window[enr_vars.evid]?(localStorage.setItem(enr_vars.evid,window[enr_vars.evid]),window[enr_vars.evid_v]&&localStorage.setItem(enr_vars.evid_v,window[enr_vars.evid_v])):(window[enr_vars.evid]=localStorage.getItem(enr_vars.evid)||"",window[enr_vars.evid_v]=localStorage.getItem(enr_vars.evid_v)||"")}catch(c){}"null"==window[enr_vars.evid]&&(window[enr_vars.evid]="",adtlgcen_Cookie.unset(enr_vars.evid));var b=window.addEventListener?"addEventListener":"attachEvent";
(0,window[b])("attachEvent"==b?"onmessage":"message",function(b){try{var c=JSON.parse(b.data);if("getUser"==c.action){var e=c.evid;if("optout"==e&&(adtlgcen_Cookie.unset(enr_vars.evid_v),adtlgcen_Cookie.unset(enr_vars.adptseg),adtlgcen.util.localStorageEnabled()))try{localStorage.removeItem(enr_vars.evid),localStorage.removeItem(enr_vars.evid_v)}catch(g){}!adtlgcen.util.isSafari()||e&&"-entered"!=e||cX.getCxenseUserId&&cX.getCxenseUserId()&&(e=cX.getCxenseUserId().replace(/:/g,"-"));window[enr_vars.evid]=
e;adtlgcen_Cookie.set(enr_vars.evid,e,2160);var f=c.vv||"";(window[enr_vars.evid_v]=f)?adtlgcen_Cookie.set(enr_vars.evid_v,f,2160):adtlgcen_Cookie.unset(enr_vars.evid_v);a()}}catch(g){}},!1);window[enr_vars.evid]&&"1"==adtlgcen_Cookie.get(enr_vars.adptset)?a():adtlgcen.util.getUserId()};window[enr_vars.dataRequest]=new DataRequest(admp_);admp_.init()};
